CREATE DATABASE customer_behavior;

USE customer_behavior;

SHOW TABLES; -- customer only

SELECT * FROM customer; -- cleaned data (ipynb)

ALTER TABLE customer
RENAME COLUMN purchase_amount TO purchase_amount_usd;

-- Insights :)

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY gender;
-- Helps companies understand which customer segment contributes more revenue for targeted marketing and product planning.
-- identify target customers



-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd)
							FROM customer);  -- where runs before select
-- Shows whether discounts attract high-value customers and whether promotions are profitable.
-- discounts worked ?


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, round(AVG(review_rating), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
-- Identifies customer-favorite products to promote, restock, and prioritize.



-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT DISTINCT shipping_type
FROM customer;

SELECT shipping_type, ROUND(AVG(purchase_amount_usd), 2)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
-- Helps analyze whether faster shipping customers spend more and prefer premium services.
-- is express shipping profitable 



-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) AS total_customers,
	   ROUND(AVG(purchase_amount_usd), 2) AS avg_spend, ROUND(SUM(purchase_amount_usd), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue ASC, avg_spend DESC;  -- lowest total_revenue first, if equal then, highest avg_spend
-- Measures the effectiveness of subscription programs on revenue and customer loyalty.
-- is loyalty and subscription inter- related



-- **Q6. Which 5 products have the highest percentage of 'purchases with discounts' applied?

/* Discount Rate = (Total Purchases / Discount Purchases)​ *100
   100.0 * discounted_purchases / total_purchases 
   eg. 
     item	discount_applied
     Shoes	        Yes
     Shoes	        No
     Shoes	        Yes
     Result = 2
     => (2 / 3) * 100 = 66.67%
     Means: 66.67% of shoe purchases used discounts :)
*/
SELECT item_purchased, COUNT(*) AS total_purchased, SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS purchased_on_discount,
	   ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
-- Shows which 'products depend heavily on discounts' and customer price sensitivity.



-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT customer_id, previous_purchases,
CASE WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
     ELSE 'Loyal'
     END AS customer_segment
FROM customer;

-- segments
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE WHEN previous_purchases = 1 THEN 'New'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
     ELSE 'Loyal'
     END AS customer_segment
FROM customer)

-- count of each segment 
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment
ORDER BY "Number of Customers" DESC;
-- Helps businesses create different strategies for new, returning, and loyal customers.




-- Q8. What are the top 3 most purchased products within each category? 
SELECT category, item_purchased, COUNT(item_purchased) AS total_orders, -- makes more sense :)
       ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased;

WITH item_counts AS(
SELECT category, item_purchased, COUNT(customer_id) AS total_orders, 
       DENSE_RANK() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT category, item_purchased, total_orders, item_rank
FROM item_counts
WHERE item_rank <=3;
-- Helps optimize inventory, recommendations, and category-wise marketing.



-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? => No :(
SELECT customer_id, subscription_status
FROM customer
WHERE previous_purchases > 5; -- figure out yes is more than no ?

SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
-- Shows whether loyal customers are more likely to subscribe to membership programs (or vice-versa).



-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- min and max age data along with revenue 
SELECT age_group, SUM(purchase_amount_usd) AS total_revenue,
       MIN(age) AS min_age, MAX(age) AS max_age
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
-- Helps companies target age-specific marketing and understand purchasing behavior across demographics.